m2m/requests/urls.py
from django.conf.urls.defaults import *

# Urls go here!

urlpatterns = patterns('requests.views',
        
        (r'^$','open'),
        (r'^(?P<page>\d*)$','open'),
        (r'^completed(/(?P<page>\d*))?$','completed'),
        (r'^deleted(/(?P<page>\d*))?$','deleted'),
        (r'^edit/(\d+)$','edit'),
        (r'^complete/(\d+)$','complete'),
        (r'^delete/(\d+)$','delete'),
		(r'^like/(?P<id>\d+)/(?P<page>\d+)$','like'),
    )

m2m/urls.py
from django.conf.urls.defaults import *
#from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#from datetime import datetime

urlpatterns = patterns('',
    # Example:
    # (r'^m2m/', include('m2m.foo.urls')),
    #(r'^api/v1/', include('fiber.api.urls')),
    #(r'^admin/fiber/', include('fiber.admin_urls')),
    #(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('fiber',),}),
    (r'^flat', include('django.contrib.flatpages.urls')),
    (r'^tos', 'faq.views.serviceTerms'),
    (r'^privacy.html', 'faq.views.privacy'),
    (r'^dmca', 'faq.views.dmca'),
    #(r'^', 'problems.views.sitewide'), # for maintenance, etc
    (r'^imaging/',include('imaging.urls')),
    (r'^monkeybutter$', 'search.views.test'),
    
    (r'^$', 'search.views.index'),
    #(r'^?q=([a-zA-Z0-9]*)$','search.views.results' ),
    (r'^search/', include('search.urls')),
    (r'^advanced/', include('advancedsearch.urls')),
    #(r'^requests', 'problems.views.requests'), # for maintenance, etc
    (r'^requests/', include('requests.urls')),
    
    (r'^polls', 'problems.views.polls'), # for maintenance, etc
    (r'^polls/', include('polls.urls')),
    
    #(r'^servers', 'problems.views.browseNet'), # for maintenance, etc
    (r'^servers/', include('browseNet.urls')),
    
    #(r'^(news|comments)/', 'problems.views.news'), # for maintenance, etc
    (r'^news/', include('basic.blog.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    
    (r'^problems/', include('problems.urls')),
    
    (r'^stats', 'problems.views.stats'), # for maintenance, etc
    (r'^stats/', include('stats.urls')),

    (r'^faq&', 'faq.views.basic'),
    (r'^faq/', include('faq.urls')),
    

    
    (r'^about/m2m$','faq.views.about',{'typeof':'m2m'}),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
)

#if settings.DEBUG:
#    urlpatterns += patterns('django.contrib.staticfiles.views',
#        url(r'^static/(?P<path>.*)$', 'serve'),
#    )

m2m/requests/models.py
from django.db import models

# Create your models here.

# a cleaned up version of the old comments model, django-ready.
class Comment(models.Model):
    CID = models.IntegerField(primary_key=True,unique=True,editable=False,)
    requestTime = models.DateTimeField()
    name = models.CharField(max_length=120,null=True,blank=True,default='Anonymous') 
    email = models.EmailField(max_length=180,null=True,blank=True) 
    completed = models.BooleanField()
    completedTime = models.DateTimeField(null=True,blank=True)
    completerComment = models.TextField(null=True,blank=True)
    completingName = models.CharField(max_length=120,null=True,blank=True) 
    completingServer = models.CharField(max_length=120,null=True,blank=True) 
    isDeleted = models.BooleanField()
    deleterIP = models.IPAddressField(null=True,blank=True)
    deletedTime = models.DateTimeField(null=True,blank=True)
    request = models.TextField()
    server = models.CharField(max_length=60, null=True,blank=True)
    requestIP = models.IPAddressField(max_length=64,null=True,blank=True)
    # ala facebook
    Likes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.request
    
    def save(self,*args,**kwargs):
        if not self.CID:
            i = Comment.objects.raw('SELECT * FROM requests_comment ORDER BY CID DESC LIMIT 1')[0]
            self.CID = i.CID+1
        super(Comment,self).save(*args,**kwargs)

m2m/requests/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
#from django.db import transaction

from m2m.requests.models import Comment
from m2m.requests.formClasses import RequestForm, ModifyForm

from datetime import datetime
# Set some nice globals here
PERPAGE = 20 # how many requests per page?

# Create your views here.

def open(request,page=1,error=''):
    '''Handles the display of the open requests. Seriously, this isn't rocket science or anything.'''
      
    try:
        page = int(page) - 1 # switch to zero indexing
        if page < 0:
            page = 0
    except Exception:
        page = 0

    # different behavior if a request was submitted
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            try:
                #from django.db import connection
    
                #cursor = connection.cursor()
                #cursor.execute('LOCK TABLES requests_comment WRITE')
                
                newRequest = Comment(
                                request=form.cleaned_data['request'],
                                name=form.cleaned_data['name'],
                                server=form.cleaned_data['server'].upper(),
                                email=form.cleaned_data['email'],
                                requestIP=request.META['HTTP_X_FORWARDED_FOR'],
                                requestTime = datetime.now()
                                )
                
                newRequest.save()
                #cursor.execute('UNLOCK TABLES')
                # successful post, return to requests page to see the result
                
                '''
#########################################################
# --- Log new request info 
#
                rom django.db import connection
                cursor = connection.cursor()
                
                cursor.execute('LOCK TABLES log, requests_comment WRITE')
                cursor.execute(
                    'INSERT INTO log (Time,Client,SearchString)\
                    VALUES (%(time)d, "%(client)s", "%(search)s")' % {
                        'time':time.mktime(time.localtime()),
                        'client': request.META['HTTP_X_FORWARDED_FOR'],
                        'search':"Request: %(query)s" % {'query':newRequest.request},
                    }
                )
                cursor.execute('UNLOCK TABLES')
                transaction.set_dirty()
                transaction.commit()
#
#
#########################################################
                '''
                
                test = 3
                return HttpResponseRedirect(reverse('requests.views.open',args=(1,)))
            except Exception, e:
                form.non_field_errors = e
                test = 2
        else:
            test = 1
    else:
        form = RequestForm()
        test = 0
    #SQL: "SELECT * FROM comments WHERE COMPLETED = False AND deleted = False ORDER BY Time DESC LIMIT %(start)s,%(depth)s"%{'start':page*20, 'depth':PERPAGE}
    
    displaySet = Comment.objects.filter(isDeleted=0,completed=0).order_by('-requestTime')  # filter out deleted and completed, order by time
    setLen = len(displaySet)
    
    displaySet = displaySet[page*PERPAGE:(page+1)*PERPAGE]# and take the appropriate slice
    
    remainder = setLen % PERPAGE # we need to do this because setLen and PERPAGE are ints
    if remainder > 0:
        remainder = 1
    linkPages = range(1,setLen/PERPAGE + remainder + 1)
        

    
    return render_to_response('requests/requests.html',
                              {
                                'title':'M2M - Requests',
                                'requests':'current',
                                'openReq':'current', 
                                'displaySet':displaySet,
                                'toprequests': Comment.objects.filter(isDeleted=0,completed=0,Likes__gt=0).order_by('-Likes')[:PERPAGE+10],
                                'page':page+1,
                                'linkPages':linkPages,
                                'setLen':setLen,
                                'test':test,
                                'form':form,
                                'error':error,
                              },context_instance=RequestContext(request)
                              )

def completed(request,page=1):
    try: page = int(page) - 1
    except Exception:
        page = 0

    
    #SQL: "SELECT * FROM comments WHERE Completed = True AND deleted = False ORDER BY CompletedTime DESC LIMIT %(start)s,%(depth)s"%{'start':page*20,'depth':PERPAGE}

    displaySet = Comment.objects.filter(isDeleted=0,completed=1).order_by('-completedTime')  # filter out deleted and not-completed, order by completedtime
    setLen = len(displaySet)
    
    displaySet = displaySet[page*PERPAGE:(page+1)*PERPAGE]# and take the appropriate slice
    
    remainder = setLen % PERPAGE # we need to do this because setLen and PERPAGE are ints
    if remainder > 0:
        remainder = 1
    linkPages = range(1,setLen/PERPAGE + remainder + 1)    

    return render_to_response('requests/requests.html',
                          {
                            'title':'M2M - Completed Requests',
                            'requests':'current',
                            'closedReq':'current',
                            'modifier':'/completed',
                            'linkPages':linkPages,
                            'page':page+1,
                            'setLen':setLen,
                            'displaySet':displaySet,
                          })


def deleted(request,page=1):
    try: page = int(page) - 1
    except Exception:
        page = 0
        
    #SQL: "SELECT * FROM comments WHERE deleted = True ORDER BY Time DESC LIMIT %(start)s,%(depth)s"%{'start':page*20,'depth':PERPAGE}
    displaySet = Comment.objects.filter(isDeleted=1).order_by('-deletedTime')  # filter out not deleted, order by time
    setLen = len(displaySet)
    
    displaySet = displaySet[page*PERPAGE:(page+1)*PERPAGE]# and take the appropriate slice
    
    remainder = setLen % PERPAGE # we need to do this because setLen and PERPAGE are ints
    if remainder > 0:
        remainder = 1
    linkPages = range(1,setLen/PERPAGE + remainder + 1)    
    
    return render_to_response('requests/requests.html',
                          {
                            'title':'M2M - Deleted Requests',
                            'requests':'current',
                            'delReq':'current',
                            'modifier': '/deleted',
                            'linkPages':linkPages,
                            'page':page+1,
                            'setLen':setLen,
                            'displaySet':displaySet,
                          },context_instance=RequestContext(request))
    

def edit(request,id):
    
    entry = Comment.objects.get(pk=id)
    
    if entry.isDeleted or entry.completed: # no editing completed or deleted things!
        return HttpResponseRedirect(reverse('requests.views.open',args=(1,)))
    
    
    if request.method == "POST":
        form = ModifyForm(request.POST,{'completingServer':"",})
        form.completingServer = ""
        if form.is_valid():
            test = 0
            #from django.db import connection
    
            #cursor = connection.cursor()
            #cursor.execute('LOCK TABLES requests_comment WRITE')
            
            entry.request = form.cleaned_data['request']
            entry.name = form.cleaned_data['name']
            entry.server = form.cleaned_data['server'].upper()
            entry.email = form.cleaned_data['email']
            entry.requestTime=datetime.now()
            
            entry.save()
            #cursor.execute('UNLOCK TABLES')
            return HttpResponseRedirect(reverse('requests.views.open',args=(1,)))
        test = form.errors
    else:
        form = ModifyForm(instance=entry,initial={'completingServer':""})
        test = 1
    
    return render_to_response('requests/modify.html',
                              {
                                'title': 'M2M - Editing Request '+id,
                                'requests':'current',
                                'openReq':'current',
                                'entry':entry,
                                'edit':True,
                                'form':form,
                                'test':test,
                                },context_instance=RequestContext(request)
                              )
    
def complete(request,id):
    from django.core.mail import send_mail

    entry = Comment.objects.get(pk=id)
    
    if entry.isDeleted or entry.completed: # no double completes! nor completing deleted things.
        return HttpResponseRedirect(reverse('requests.views.completed',current_app='requests'))
    
    if request.method == 'POST':
        form = ModifyForm(request.POST)
        if form.is_valid():
            if len(form.cleaned_data['completingServer']) > 0:
                try:
                    
                    entry.completed = True
                    entry.completingName = form.cleaned_data['completingName']
                    if len(form.cleaned_data['completingServer']) > 1:
                        entry.completingServer = form.cleaned_data['completingServer'].upper().replace('\\','')
                    else:
                        entry.completingServer = request.META['HTTP_X_FORWARDED_FOR']
                    entry.completerComment = form.cleaned_data['completerComment']
                
                    entry.completedTime = datetime.now()
                    
                    entry.save()
                    recipients = ['haak.erling@gmail.com']

m2m/templates/requests/modify.html
{% extends "base_page.html" %}
{% load request_extras %}
{%block stylin %} <link rel="stylesheet" type="text/css" media="screen" href="/media/styles/requests.css" /> {% endblock %}
{%block scriptin%} 
<script>
$(function(){
	$("#modifier :input[title]").tooltip({
                position:"center",
                offset: [-2,10],
                effect: "fade",
                opacity: 0.7
            });
        });        
</script>
{% endblock%}

{%block content %}
<div class="tablewrap">
    <table>
        <tr class="{% cycle 'darkrow' '' %}" style="font-size:12px;line-height:18px;height:24px;">
                <td style="filter:alpha(opacity=50);-moz-opacity:.50;opacity:.50;">
                    {%if entry.server%}
			<a href="{% url browseNet.views.deepBrowse 'H' entry.server|hid %}">
                        <strong>\\{{entry.server}}</strong></a>
		    {% endif %}
		    {% if entry.server and entry.name %}
			{%if entry.name != 'Anonymous' %}
			    <strong> - {{entry.name}}</strong>
			{% endif %}
                    {%else%}
                        {%if entry.name != 'Anonymous' and entry.name != ''%}
                            <strong> {{entry.name}} </strong>
                        {%else%}
			    Anonymous
                        {%endif%}
                    {%endif%}
                </td>
                <td style="filter:alpha(opacity=50);-moz-opacity:.50;opacity:.50;" align="right">
                    {{entry.requestTime|dateSlice}}
                
                    <strong>
                        {%if complete or delete%}<a  href="{% url requests.views.edit entry.CID %}">Edit</a>{%endif%}
                        {% if edit or delete %}<a  href="{% url requests.views.complete entry.CID %}">Complete</a>{%endif%}
                        {% if complete or edit%}<a href="{% url requests.views.delete entry.CID %}">Delete</a>{%endif%}
                    </strong>
                    
                </td>
            </tr>
            <tr class="{% cycle 'darkrow' '' %}" style="font-size:12px;line-height:18px;height:24px;">
                <td class="commentCell" colspan="2"><p>{{entry.request|toHTML}}</p></td>
            </tr>
    </table>
</div>
{%endblock%}
{{test}}
{% block extraContent %}
<div id="requestForm" class="tablewrap">
    <form id="modifier" action='' method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <table>
                {% if edit %}
                <input type="hidden" name="completingServer" value="none" id="id_completingServer" />
            <tr><td rowspan="4" class="required">
                        <label>Your correction/addition/notation:<br />
                        {{ form.request }}
                        </label>
                    </div>
                </td>
                <td>
                    <label>Your name: <br />
                    {{ form.name }}
                    <!--<input  type="text" value="{{entry.name|default:''}}" name="name" size="20" placeholder="Anonymous" pattern="([a-zA-Z])*" required="false" />-->
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Your server (optional):<br />
                    {{form.server}}
                    <!--<input  type="text" name="email" value="{{entry.email|default:''}}" size="20" placeholder="LABRYCE" pattern="([a-zA-Z0-9])*" required="false"/>-->
                    </label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>Your email (optional):<br />
                    {{form.email}}
                    <!--<input  type="email" name="contact" value="{{entry.contact|default:''}}" placeholder="your_name@hmc.edu" pattern="([a-zA-Z0-9])*@hmc.edu" required="false"
                            title="You'll get an email when the request is completed."/>-->
                    </label>
                </td>
            </tr>
        {%else%}
            <div style="display:none;">
                {{form.request}}
            </div>
            <tr>
                <td rowspan='3'>
                    <label>Your comment:<br />
                    {{ form.completerComment }}
                    </label>
                </td>
                <td>
                    <label>Your name (optional): <br />
                    {{ form.completingName }}
                    <!--<input  type="text" value="{{entry.name|default:''}}" name="name" size="20" placeholder="Anonymous" pattern="([a-zA-Z])*" required="false" />-->
                    </label>
                </td>
            </tr>
            <tr>
                <td class="required">
                    <label>Your server:<br />
                    {{form.completingServer}}
                    <!--<input  type="text" name="email" value="{{entry.email|default:''}}" size="20" placeholder="LABRYCE" pattern="([a-zA-Z0-9])*" required="false"/>-->
                    </label>
                </td>
            </tr>
        {%endif%}
            <tr>
                <td><input type="submit" /></td>
            </tr>
        </table>
    </form>
    {% if form.errors %}
        {{form.errors}}
    {%endif%}
</div>
{% endblock %}

m2m/templates/requests/requests.html
{% extends "base_page.html" %}
{% load request_extras %}
{% block title %} M2M -{% if closedReq %} Completed{%endif%}{%if delReq%} Deleted{%endif%} Requests{%endblock%}
{%block stylin %} <link rel="stylesheet" type="text/css" media="screen" href="/media/styles/requests.css" /> {% endblock %}

{% block scriptin %}
<script src="/media/scripts/requests.js"></script>
<script>
// can't move this out of page - context dependent variables.
function likeHandler(){
    $('.likeform').submit(function(){
        cid = $(this).attr('id');
        $.ajax({
            type: "POST",
            data: $(this).serialize(),
            url: "/requests/like/"+cid+"/{{page}}",
            cache: false,
            dataType:'html',
            success: function(html,textStatus){
                $('#'+cid+" em").load('{% url requests.views.open page%} #'+cid+' em');
                $('#'+cid+" button").replaceWith("Thanks!");
            },
            error: function( XMLHttpRequest, textStatus, errorThrown){
                $('#'+cid+" button").replaceWith("Sorry, no");
            }
        
        });
        return false;
    });
}
</script>
{% endblock %}

{% block externalContent %}
{% if openReq %}<a id="tabform"><div id="followTab">
Request!
</div></a>
<div id="simpleModal"><a class="green button" id="closeSimple"><span>close</span></a></div>{% endif %}
{% endblock %}

{% block content %}
    
<section>
<div style="text-align:center;">
<div class="error"><ul>{% for error in form.non_field_errors %}<li>{{error|escape}}</li>{%endfor%}</ul></div>
    There {{setLen|pluralize:"is,are"}} {{setLen|default:0}}
    {% if openReq %}open{% endif %}{% if closedReq %}completed{%endif%}{% if delReq %} deleted {% endif %}
    request{{setLen|pluralize}}.
</div><br />
</section>

<span class="error">{{error}}</span>


{% if displaySet %}

<div style="position:relative;"><strong>Page:
{% for number in linkPages %}{%spaceless%}
    {% if number == page %}
        {{number|default:'1'}}
    {% else %}
        {%if openReq %}<a href="{% url requests.views.open number%}">{{number}}</a>{%endif%}
        {%if closedReq%}<a href="/requests{{modifier}}/{{number}}">{{number}}</a>{%endif%} {# why won't {% url %} work for these two!? #}
        {%if delReq%}<a href="/requests{{modifier}}/{{number}}">{{number}}</a>{%endif%}
    {% endif %}
{%endspaceless%}
{% endfor %}</strong>
</div>

{% if openReq %} 
<div class="requeststop">
<table class="requestWrap">
    <thead>
        <tr><td colspan=3 style="text-align: center;">Top Requests</td></tr>
    </thead>
    <tbody>
    {% for request in toprequests %}
        <tr>
        <td style="padding-right: 5px;padding-left: 2px;">{{request.request|toHTML|truncatewords_html:20}}</td>
        <td style="text-align: center; padding-right: 5px;"> 
            <form class="likeform" action="" id="{{entry.CID}}" method="POST">
                        {% csrf_token %}
                        <input type=hidden name="id" value="{{entry.CID}}"/>
                        <input type=hidden name="page" value="{{page}}"/>
                        <button class="as_link" title="like this" type=" name="liker" onclick="doLike({{request.CID}})">
                            {{request.Likes}} like{{request.Likes|pluralize}}
                        </button>
                    </form>
        </td>
        <td class="actions"><a  href="{% url requests.views.complete request.CID %}">Complete</a></td>
        </tr>    
    {% endfor %}
    </tbody>
</table>
</div>
{% endif %}

<div class="chronrequests{% if openReq %} open{%endif%}">
    {% for entry in displaySet %}
    
        <table class="requestWrap">
            <tr class="requestmeta" style="">
                <td class="requestername">
                    {%if entry.server%}
                        <a href="{% url browseNet.views.deepBrowse 'H' entry.server|hid %}">\\{{entry.server}}</a>
                    {%endif%}
                    {% if entry.server and entry.name%}
                        {%if entry.name != 'Anonymous' %}
                            <strong> - {{entry.name}}</strong>
                        {%endif%}
                    {%else%}
                        {% if entry.name != 'Anonymous' and entry.name != ''%}
                            <strong>{{entry.name}}</strong>
                        {%else%}
                            Anonymous
                        {%endif%}
                    {%endif%}
                    {% if entry.completed == 1 %}
                        {% if entry.completingName != 'Anonymous' and entry.completingName != None and entry.completingName != ''%}
                            - completed by {{entry.completingName}} (<a href="{% url browseNet.views.deepBrowse 'H' entry.completingServer|hid %}">\\{% firstof entry.completingServer %}</a>)
                        {%else%}
                            - completed by <a href="{% url browseNet.views.deepBrowse 'H' entry.completingServer|hid %}">\\{{entry.completingServer}}</a>
                        {%endif%}
                    {%endif%}
                </td>
                <td align="right" class="actions">
                    {%if closedReq%}Completed: {{entry.completedTime|date:"m/d/Y"}}, Requested:{%endif%}
                    {%if delReq%}Requested:{%endif%}
                        {{entry.requestTime|date:"m/d/Y"}}
                    {%if openReq%}
                            <a  href="{% url requests.views.edit entry.CID %}">Edit</a>
                            <a  href="{% url requests.views.complete entry.CID %}">Complete</a>
                            <a href="{% url requests.views.delete entry.CID %}">Delete</a>
                    {% endif %}
                </td>
            </tr>
            <tr class="requestbody">
                <td class="commentCell" colspan="2"><p>{{entry.request|toHTML}}</p>
                {%if closedReq and entry.completerComment %}
                    <strong>{{entry.completingServer|default:"Completer"}}'s Comment:</strong><br />
                    <p>{{entry.completerComment|toHTML}}</p>
                {% endif %}
                {% if openReq or closedReq %}
                    <div class="likes">
                    {% if openReq %}
                    <form class="likeform" action="" id="{{entry.CID}}" method="POST">
                        {% csrf_token %}
                        <input type=hidden name="id" value="{{entry.CID}}"/>
                        <input type=hidden name="page" value="{{page}}"/>{%endif%}
                        <em>{{entry.Likes}} like{{entry.Likes|pluralize}}</em>{%endif%}
                        {% if openReq %}-
                        <button class="as_link" title="like this" type=" name="liker" onclick="doLike({{entry.CID}})"><strong><span>like this</span></strong></button>
                    </form>
                    
                    </div>
                        {% endif %}
                </td>
            </tr>
        </table>
    {% endfor %} 
    </div>
    
<div style="position:relative;"><strong>Page:
    {% for number in linkPages %}
        {% if number == page %}
            {{number|default:'1'}}
        {% else %}
            {%if openReq %}<a href="{% url requests.views.open number%}">{{number}}</a>{%endif%}
            {%if closedReq%}<a href="/requests{{modifier}}/{{number}}">{{number}}</a>{%endif%} {# this is bull #}
            {%if delReq%}<a href="/requests{{modifier}}/{{number}}">{{number}}</a>{%endif%} {# this is also bull #}
            
        {% endif %}
    {% endfor %}
    </strong>
    </div>
{% endif %}

{% endblock %}

{% block extraContent %}

{% if openReq %}
    <script>

    </script>
    
    <br />
    <div id="requestForm">
        <form id="requester" action='' method="POST">
            {% csrf_token %}
            
                    <div id="requestComment"><label for="id_request">Your comment/request/idea:</label><br />
                    {{form.request}}
                    </div>
                    
                    <div id="noncommentrequest">
                    <ul >
                        <li><label for="id_name" class="required">Your name:</label>
                        {{ form.name }}
                        </li>

                        <li id="requestServer">
                        <label for="id_server">Your server:</label>{{form.server}}
                        </li>

                        <li id="requestEmail"><label for="id_email">Your email:</label>
                        {{form.email}}
                        </li>
                    </ul><div id="requestSub">
                    <a class="green button" id="submitrequest"><span>Submit</span></a>
                    </div></div>
                    

        </form>
        {% if form.request.errors %}
                    <div class="error">
                        {% for error in form.request.errors %}
                            {{ error|escape}}<br/>
                            {%endfor%}
                    </div>
                    {%endif%}
    </div>
{% endif %}

{% endblock %}