m2m/faq/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('faq.views',
    (r'^servers','servers'),
    (r'^','basic'),
    )

m2m/urls.py
from django.conf.urls.defaults import *
#from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#from datetime import datetime

urlpatterns = patterns('',
    # Example:
    # (r'^m2m/', include('m2m.foo.urls')),
    #(r'^api/v1/', include('fiber.api.urls')),
    #(r'^admin/fiber/', include('fiber.admin_urls')),
    #(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('fiber',),}),
    (r'^flat', include('django.contrib.flatpages.urls')),
    (r'^tos', 'faq.views.serviceTerms'),
    (r'^privacy.html', 'faq.views.privacy'),
    (r'^dmca', 'faq.views.dmca'),
    #(r'^', 'problems.views.sitewide'), # for maintenance, etc
    (r'^imaging/',include('imaging.urls')),
    (r'^monkeybutter$', 'search.views.test'),
    
    (r'^$', 'search.views.index'),
    #(r'^?q=([a-zA-Z0-9]*)$','search.views.results' ),
    (r'^search/', include('search.urls')),
    (r'^advanced/', include('advancedsearch.urls')),
    #(r'^requests', 'problems.views.requests'), # for maintenance, etc
    (r'^requests/', include('requests.urls')),
    
    (r'^polls', 'problems.views.polls'), # for maintenance, etc
    (r'^polls/', include('polls.urls')),
    
    #(r'^servers', 'problems.views.browseNet'), # for maintenance, etc
    (r'^servers/', include('browseNet.urls')),
    
    #(r'^(news|comments)/', 'problems.views.news'), # for maintenance, etc
    (r'^news/', include('basic.blog.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    
    (r'^problems/', include('problems.urls')),
    
    (r'^stats', 'problems.views.stats'), # for maintenance, etc
    (r'^stats/', include('stats.urls')),

    (r'^faq&', 'faq.views.basic'),
    (r'^faq/', include('faq.urls')),
    

    
    (r'^about/m2m$','faq.views.about',{'typeof':'m2m'}),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
)

#if settings.DEBUG:
#    urlpatterns += patterns('django.contrib.staticfiles.views',
#        url(r'^static/(?P<path>.*)$', 'serve'),
#    )

m2m/polls/models.py
from django.db import models
import datetime


# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def was_published_today(self):
        return self.pub_date.date() == datetime.date.today()
    was_published_today.short_description = 'Published today?'
    
    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField()
    
    def __unicode__(self):
        return self.choice

m2m/faq/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from django import forms

import random

# Create your views here.

class FAQForm(forms.Form):
    error_css_class='error'
    required_css_class = 'required'
    
    # just for fun, placeholder questions
    questions = ['I swear to god, if you spam me...']*5
    questions += ['Why are you so handsome, M2M?', 
                'Who\'s your daddy?', 
                'How *you* doin\'?',
                'Anyone for tea?',
                'Fezzes are cool.',
                'Are you sure about that?',
                ]
    
    def __init__(self,*args,**kwargs):
        forms.Form.__init__(self,*args,**kwargs)
        
        self.fields['question'] = forms.CharField(widget=forms.Textarea(attrs={
                    'rows':'9',
                    'cols':'50',
                    'placeholder':random.choice(self.questions),
                    }),required=True)
        
    
def sendFAQMail(recipients,section,request):
    from django.core.mail import send_mail
    # No matter what, we should have a form.
    form = FAQForm(request.POST)
    if form.is_valid():
        # Set the appropriate subject lines...
        subject = "FAQ - %s" % section
        q = form.cleaned_data['question']
        send_mail(subject,q,'faq@m2m.st.hmc.edu',recipients)
    
def basic(request):
    ''' displays the generic faq, without any specialization '''
    
    if request.method == 'POST':
        sendFAQMail(['haak.erling@gmail.com',],'Basic',request)
    
    form = FAQForm()
        
    return render_to_response('faq/basic.html',
                                {
                                'title': 'M2M - FAQ',
                                'faq': 'current',
                                'basic':'current',
                                'section':'basic',
                                'form' : form,
                                },context_instance=RequestContext(request))
                              
def servers(request):
    ''' displays the server-specific faq'''
    
    # This is stupid, duplicated code, but django is a big bitch about 
    # dedicated POST-processing views.
    
    if request.method == 'POST':
        sendFAQMail(['haak.erling@gmail.com',],'Server',request)
    
    random.seed()
    form = FAQForm()
    
    return render_to_response('faq/server.html',
                                {
                                'title': 'M2M - FAQ:Servers',
                                'faq':'current',
                                'server':'current',
                                'section':'servers',
                                'form': form,
                                },context_instance=RequestContext(request))
                                
def about(request,typeof='m2m'):
    ''' handles the about pages. This seemed like a good place to put them.'''
    if typeof == 'm2m':
        return render_to_response('faq/m2m.html',
                                {
                                'title': 'M2M - About: M2M',
                                'about':'current',
                                'section':'about',

                                },context_instance=RequestContext(request))
    
    return render_to_response('faq/basic.html',
                                {
                                'title': 'M2M - About: M2M',
                                'faq':'current',
                                'section':'about',

                                },context_instance=RequestContext(request))
                                

def serviceTerms(request):

    return render_to_response('faq/tos.html',
                            {'title':'M2M - Terms of Service'},
                            )
                            
def dmca(request):
    return render_to_response('404.html')
    
def privacy(request):

    return render_to_response('404.html')

m2m/templates/faq/basic.html
{% extends 'base_page.html' %}


{% block stylin %}
<link rel="stylesheet" type="text/css" media="screen" href="/media/styles/faq.css" />
{% endblock %}




{% block content %}
<div class="faqWrap">
<article>
		<header>
			<h1>
				What are the rules?
			</h1>
		</header>
		<div class="faqResponse">
			<h2> Short Answer: </h2>
			<p>
				<ol>
					<li> <h3>Don't be a jackass.</h3> </li>
					<li> <h3>Don't be a dumbass.</h3> </li>
					<li> <h3>Don't be a snitch...ass.</h3> </li>
				</ol>
			</p>
			<h2> Long Answer: </h2>
			<p>
				<ol>
					<li> <h3>Don't be a jackass.</h3> 
						<p> You learned about this at orientation, and <em>(surprise!)</em> it applies
						for the entirety of your Mudd career, everywhere, at all times. Ideally you'll
						choose to apply it afterwards, too, but it applies whether you like it or not
						while you're here. And you really ought to like it, unless you're a douchebag.</p>
						<p> You're not a douchebag, are you? </p>
					</li>
					<li> <h3>Don't be a dumbass.</h3> 
						<p> Look, I'll be honest. I don't know where the files on the network come from, for
						sure, and I definitely don't want to know &#8212 deniability, etc., etc. &#8212 but
						I can certainly imagine scenarios where certain elements of the law might frown on
						the methods used.</p>
						<p> Just, be careful. Students DO get cease-and-desist letters, which the school takes
						seriously, and you need to be aware of that. Just because the Network is safe, does <strong>NOT</strong>
						mean that it is safe to behave as if the Internet-at-large is just a bigger version of it.
						Don't be fooled; M2M is family, the FBI &#8212 though another 3-character association &#8212
						is not. At least not in the cool-uncle way that M2M is.</p>
						<p> Don't be stupid. I don't want bad shit to happen to you because of careless seeding.</p>
						<p> ...Or, uh, whatever it's called.</p>
					</li>
					<li> <h3>Don't be a snitch...ass.</h3> 
						<p> Your use of the search functionality on this site implies that you do not believe its
						existence violates the honor code. If this is not the case, leave; it's in the 
						<a href="{%url faq.views.serviceTerms%}">terms of service</a>,
						which you should have read before utilizing any function of this site.</p>
						<p> In a nutshell, it says that it's <em>your bad</em> if shit goes down, and M2M is not
						your babysitter. I think that's fair. It also says M2M can change and improve and grow etc.,
						etc. All that stuff. It also says that M2M will not break this rule unless the Honor Code,
						as interpreted by M2M, requires it - the Honor Code supersedes all.
						<p> Likewise, utilizing the Network implies that you're okay with its existence. I can't
						make you agree to this, but Rule #1, guys; Rule #1.</p>
						<p> But the purpose of this rule is to make sure that nobody violates Rule #2 and starts posting
						all over the Internet-at-large about how great our Network is. That kind of shit <em>gets noticed</em>,
						Nancy (funwiki, I'm looking at you). </p>
						<p> Please, please, please, for the love of whatever you hold where God traditionally would be held,
						do not do this.</p>
						<p><strong> Rule #3: The Network does not exist, has never existed, and will never exist. Behave accordingly.</strong></p>
					</li>
				</ol>
			</p>
		</div>
    </article>
    <article>
		<header>
			<h1>
				What is "The Network"?
			</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer: </h2><p> A bunch of shit that you can take. </p>
			
			<h2> Long Answer: </h2><p>
			The Network is the name given to the collective intellectual wealth comprised by Mudd's student
			run servers. It may or may not be, strictly speaking, legal, but because of the
			closed nature of Mudd's intranet, it's protected from outside scrutiny.</p>
			<p>This means that once something <em>is</em> on the Network, it's safe to grab for yourself,
			whatever it might be.</p>
			<p> <strong>Disclaimer: Rule #2</strong></p>
		</div>
    </article>
	<article>
		<header>
			<h1>
				What is M2M?
			</h1>
		</header>
		<div class="faqResponse">
			<h2> Short Answer: </h2><p>Your lord and savior, the gateway to paradise. </p>
			
			<h2> Long Answer: </h2><p>
			M2M is a search engine, which indexes the files hosted by the servers on the Network. 
            The logo of M2M is meant to symbolize its purpose: it provides a mapping from the set
            of Mudders onto the set of Mudders. </p>
            <p>You can search for whatever you want, and if it's publically available, and older than 
            about 23 hours, M2M will show you where it is. Sometimes you can directly download it from
			the search results page, you lucky late-comers you.
			</p>
            <p> If you're really curious about M2M, specifically, you can check out this super secret 
            <a href="{% url faq.views.about%}">about page</a>.
		</div>
	</article>
	<article>
		<header>
			<h1>
				Who are you?
			</h1>
		</header>
		<div class="faqResponse">
			<h2> Short Answer: </h2><p>See above. </p>
			
			<h2> Long Answer: </h2><p>
			A question that, potentially, has no answer &#8212 although it seems already to have more answers
			than it knows what to do with. If you're really interested in this question, allow me to point
			you to a few excellent resources:
			<ul>
				<li> <a href="http://existentialquestions.wordpress.com/"> A community </a>of like-minded questioners</li>
				<li> <a href="http://en.wikipedia.org/wiki/Existentialism">Wikipedia</a>, which you should probably read before posting on the above</li>
				<li> <a href="http://books.google.com/books?id=jDSMMg7QmSMC&printsec=frontcover&dq=who+am+i&source=bll&ots=lPZAfOFhhy&sig=vmjaPPNdaFOvLFWT_Rk34w4YbuQ&hl=en&ei=ChK9TfiwCIiCsQP346HPBQ&sa=X&oi=book_result&ct=result&resnum=21&ved=0CLMBEOgBMBQ#v=onepage&q&f=false">
						A book</a>, for those of you who prefer lies over truth</li>
						<li> <a href="http://reallifespirituality.com/who-am-i/">Or this</a>, for those who prefer lies over still other lies</li>
				<li> <a href="http://www.psychologytoday.com/blog/shift-mind/201006/who-am-i"> In case you're not sure why you're driven to ask this</a>,
						lying awake for hours at night, with its burning implications tortuously full of uncertainty and fear</li>
			</ul>
			But seriously, my name is Haak.
			</p>
		</div>
	</article>	
	<article>
		<header>
			<h1>
				What is a server?
			</h1>
		</header>
		<div class="faqResponse">
			<h2> Short Answer: </h2><p>A computer that has shit on it. </p>
			
			<h2> Long Answer: </h2><p>
			Okay, so, I know they say there's no such thing as a dumb question, but if you're at
			this school, and you need to ask this question, then...something might have gone wrong
			with the admission process. I'm just saying. In any event, I'm sure there is someone within
			20 feet of you who is not only able but <em>willing</em> to wax poetic about what it means to be a
			'server' on the Network.</p>
			<p>Briefly, a server is any computer that is configured to share things on the Mudd network.
			At least, that's what I will mean by 'server' anytime you see it on this site, unless specifically
			redifined elsewhere.</p>
		</div>
	</article>
	<article>
		<header>
			<h1>
				Can I run a server?
			</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer: </h2><p> No &#8212 a server runs you. Or maybe that's just M2M.</p>
			
			<h2> Long Answer: </h2><p>
			See the <a href="{% url faq.views.servers %}">server FAQ</a> for more about
			setting up and running your own server.</p>
		</div>
	</article>
	<article>
		<header>
			<h1>
				Is "Because We're Family" really trademarked?
			</h1>
		</header>
		<div class="faqResponse">
			<h2> Short Answer: </h2><p> For all intents and purposes, yes.</p>
			<h2> Long Answer: </h2><p>
				It turns out that <a href="http://www.uspto.gov/smallbusiness/trademarks/registering.html">you don't need to register something as a trademark</a> in order to mark it as a trademark with "&trade;". As long as
				you have a legitimate use for the mark, you can establish rights to use it as a trademark (in M2M's case, the use is legitimate: 
				a tagline). What you'll notice, however, is the lack of the "&reg;" symbol, which is illegal to use unless USPTO has officially 
				recognized your trademark, which requires that you have filed an application to get it Federally registered.
			</p><p>
				Since M2M strives to obey the law in all things, we only claim rights based on legitimate use.
			</p>
		</div>
	</article>
</div>
{% endblock %}

{% block extraContent %}
<div class="questionWrap">
<h1> Still got questions? </h1>
<form action="" method="POST">
{% csrf_token %}
<label for="id_question"> <h2>Hit me up.</h2> </label><br/>
{{form.question}}<br/>
<input type=submit value="Ask M2M!"/>
</form>
</div>
{% endblock %}

m2m/templates/faq/m2m.html
{% extends "faq/basic.html"%}

{% block content %}
<h1> A (Not-So) Brief History of M2M </h1>
<p>So, you want to learn about M2M, do you? Well, we applaud your curiosity. The history of M2M is
a murky thing, full of mystery and gaps; at its beginning, we think, nobody realized that it would
eventually become such a general, school-wide resource. But, we digress. we shall allow one far more
knowledgable than us to speak upon the history of this hallowed domain (his words used without permission):
</p>
<h2> Before SU2010 </h2>
<blockquote><p>The earliest network existed largely through Samba Explorer and some primitive
 and unreliable indexing software. A prolific pornography purveyor, let's call him D, 
 necessitated the need for a better search engine; his excel spreadsheets left a lot 
 to be desired. This led to M2M, which was probably in its second incarnation when I 
 started school (I was actually interviewed by the person who made the original, original 
 M2M - he instantly knew what my resume was hinting at). This M2M was painfully slow as it 
 was just doing LIKE queries, and there was no additional functionality. I think it was using 
 FemFind to do its crawling?</p>
<p> For a networking class, a guy named F made a much faster but still suck-ass M2M, which he 
called M2M2 and which co-existed with the other M2M for a brief period of time. After that 
original M2M disappeared several smaller, less well-known M2Ms surfaced, most notably from W and 
R -- who briefly gave West the ability to queue up music on the speakers from within M2M. M2M2 
ultimately won the popularity race, however, and the school embraced it.</p>
<p>Unsatisfied with the lack of color coordination and search granularity on M2M2, I decided to make 
my own M2M instead of doing stems homework. (I wanted to be able to search directories for music 
artists, mostly.) My M2M used a modified version of ffsearch for crawling and sphinx for search 
indexing, and it made requests a little more possible. It originally ran on my 1st-gen Macbook 
Pro (with corrupt RAM), and later on an iMac (donated to the school by R) with a corrupt graphics card.</p>
<p>After I left, a spry frosh took the reigns and started chopping up M2M by porting it to Django.</p>
<p>Despite the hazy ethics of M2M, the benefit it has provided to numerous Mudders who have all tried 
to re-create it in their own special way is unquestionable. It's also been the watchdog of HMC's changing 
interests and habits, and there's so much analysis you could do with its data... 
(just a start: http://i.imgur.com/iOFz3.png).</p></blockquote>

<p>Yea, you have just read the words of the Maestro, Bryce Lampe, who created the 'blue' look of 
the page you are now upon. Much has changed since his graduation in 2010, and the passing of M2M
into the hands of the next generation.</p>
<h2> SU2010 - SU2013 </h2>
<p> That spry frosh was Haak Saxberg, class of 2013, and the port to Django and Python has long since 
been completed. Although Bryce originally intended to hand M2M to a committee of
adminstrators, Haak became disillusioned with their lack of work and enthusiasm for the project.</p>
<p> The other members of the committee were not consulted in the decision-making process after the 
summer of 2010, and by the end of fall 2010, could safely be considered disbanded.</p>
<p>As it was handed down to him, like Bryce said, it was hosted from a quite pathetically
(but endearingly) disfunctional iMac, whose graphics card would only work in freezing temperatures or when
booted into safe mode. The data, which is really the treasure trove of M2M, was hosted on a school server,
for redundancy's sake. This was an important upgrade introduced by Bryce; before him, the iMac hosted 
everything about the site. Since the iMac is, at best, unstable, this was a dangerous sitation. Every day,
the risk was very real that not only the website but the file data would be lost. Moving the raw database
to a separate, backed-up server removed this fear.</p>
<p>However, the transfer of power was not as smooth as it could have been; some of the permissions
necessary to deal with certain issues were never transferred to Haak after Bryce's graduation. This caused
several service outages in the fall of 2010.</p>
<p>Uncomfortable with relying on school resources for the running of the site for numerous reasons, 
and fucking annoyed at not having the necessary permissions to fix serious issues, Haak 
decided to do something about it. Investing his sweat, blood, and tear-drenched money into the project,
he transferred all of M2M's mighty database into a more student-controlled medium.</p>
<p>M2M is no longer hosted on that iMac, nor does it use the permanent student share on
a school-owned server. It is a system of three computers: the web-crawler, which is still on that
ancient iMac, the webserver, and its own, dedicated data server. Further differences that Haak
implemented: whereas the elder version used Subversion as its version control system, M2M now uses
Git, which is better in every way; unfortunately, this also meant that it no longer has a pretty,
web-enabled repository browser. Subtle changes were also made to the styling of the page; rounded
table borders, enhanced requests, nicer form layouts, the FAQ secion, this about section,and a 
cleaner news page (with working comments!).</p>
<p>In the fall of 2010, an...extension, if you will, to M2M was created by Marquis Wang. Called M2M Movies,
it was a specialized version of M2M: tied into an external movie database, it provided metadata that the
core M2M simply did not at the time, but it only searched movies. Marquis was also the source of the
direct-serving idea, which was slow to catch on among servers but an important usability improvement.
</p>
<p> Inspired by the idea of meta-data enhanced searching, the core M2M undertook to integrate and improve
on this idea. Over the spring, summer, and fall of 2011 work progressed on including Movie, Music, and TV Show
metadata in search results, where applicable.
</p>
<p> Simultaneously, Portal was finally declared worthless - especially after a Pomona student (honestly, a 
Pomona student? Disgraceful.) created a prettier, more functional version of it. The only thing this evolved version
didn't do was actually allow you to register courses. But we wanted the searches to be sane, the display of course 
info to be sane, the use of the FUCKING BACK BUTTON. That's not too much to ask. So, M2M went to work.</p>
<p> With a great deal of help from Josiah Gaskin and Sarah Johnson, work began over the summer of 2011 on a
Mudd-ified Portal. The real goal, of course, was to beat Pomona at their own game because fuck those guys for
thinking their level is as high as ours.</p>
<p> In FA11, the site was given a facelift - moving nearly completely away from its original design, M2M was given
a lighter color scheme, better visual cohesion, and (most importantly) an easier-to-manage backend design.

{% endblock %}

{% block extraContent %}

{% endblock %}

m2m/templates/faq/server.html
{% extends 'faq/basic.html' %}

{% block content %}

<div class="faqWrap">


    <article>
		<header>
			<h1>
				Who runs servers?
			</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer: </h2><p> At HMC, select students. </p>
			<h2>Long Answer: </h2><p>
			You do! You, being the students, as distinct from the school itself (which has its own
			servers, but with which M2M does not, at this time, truck). And probably not you, since
			you're looking at this FAQ. But, hey, you never know.</p>
			<p> Anybody can run a server -- your neighbors might, your friends might -- if you're not
			careful, even YOU might be running a server right now.</p>
			<p> But who, specifically, runs servers? Well, I run M2M (obviously). But a complete list of
			all the people who run servers, and which servers they run, is a bit beyond the scope of this
			site. Not to mention my interest.</p>
		</div>
    </article>
    <article>
		<header>
			<h1>
				How do I run a server?
			</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer: </h2><p>Blood sacrifice, and a liberal sprinkling of baby's tears</p> 
			<h2> Long Answer:</h2>
			<p>On purpose?</p>
			<p> It's a simple-yet-difficult process, running a server. Here's what you'll need, at the
			very least:
			<ul>
			<li>(1) computer, with keyboard</li>
			<li>(1) ethernet cord</li>
			<li>(1) email address </li>
			<li> the ability to read (nice; one down already, amirite)</li>
			<li> the ability to type, or a friend who you trust and can type for you </li>
			</ul>
			These are your tools. Now, for the meat:
			<ol>
			<li> Choose a name for your server. This is the most important goddamn step, because you are saddled with
			this fucking name forever, unless you want to be a dick and make CIS do more work than they ought to.
			They get enough flak (sometimes deservedly) and do not need extra shit to do. Rule #1.</li>
			<li> Get your ass to the<a href="http://www.hmc.edu/about/administrativeoffices/cis1/forms/ipreq.html">
			Static IP Request Form</a>, and fill it out. Your reason for the request should be something like 
			"local ssh access"; they don't, in my experience, ask too many questions, and will complete
			your order within a week. You'll get an email confirmation when it's done, with the details.</li>
			<li> Follow CIS's instructions about configuring your network settings. If you don't know how to
			do this, check out <a href="http://tinyurl.com/3svamfp">this resource</a> for all the info you need.</li>
			<li> Get SAMBA sharing enabled; windows has this automatically, I think, since it's their protocol,
				but macs and unix will have to do some (not much) voodoo. I would recommend against installing
				Samba4 just yet, because it doesn't work properly.</li>
			<li> Set up your samba shares, a topic which you can find plenty of information on yourself. </li>
			<li> Put content in your samba shares </li>
			</ol>
			Annnnd that's all there is to it.</p>
			
		</div>
    </article>	
	<article>
		<header>
			<h1> What is direct serving?</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer:</h2><p>Letting people download through M2M.</p>
			<h2>Long Answer:</h2>
			<p>
			If you love your downloadees, you can configure your server to allow M2M to access them directly,
			instead of forcing people to use their browsers for SAMBA linking. This isn't much of an improvement
			for those people searching on a Mac or Unix box - those OS's handle samba links sanely.</p>
			<p>It <em>is</em> a huge improvement for Windows users, who previously had to navigate to files 
			manually in their explorers. Let me tell you, that is a pain.</p>
			<p>Direct serving allows everybody to download through their browsers, rather than samba, using HTTP
			requests.</p>
		</div>
	</article>
	<article>
		<header>
			<h1> How do I set up direct serving?</h1>
		</header>
		<div class="faqResponse">
			<h2>Short Answer:</h2><p>Depends on your server-set up.</p>
			<h2>Long Answer:</h2>
			<ol>
				<li> Install your webserver of choice, if you don't already have one (I recommend Apache or NGINX).</li>
				<li> Set up a normal host, but change it so that it listens on port 13213 instead of 80.</li>
				<li> Configure it so that it treats every file as an application, rather than something a browser knows
				how to serve.</li>
				<li> create a directory with symlinks to your samba share directories, and set that as the root of your host.</li>
				<li> Let me know that you've set up direct serving.</li>
			</ol>
		</div>
	</article>
</div>

{% endblock %}