basic/places/urls.py
from django.conf.urls.defaults import *
from basic.places import views as place_views


urlpatterns = patterns('',
    url(r'^cities/(?P<slug>[-\w]+)/$',
        view=place_views.city_detail,
        name='place_city_detail'),

    url(r'^cities/$',
        view=place_views.city_list,
        name='place_city_list'),

    url(r'^types/(?P<slug>[-\w]+)/$',
        view=place_views.place_type_detail,
        name='place_type_detail'),

    url(r'^types/$',
        view=place_views.place_type_list,
        name='place_type_list'),

    url(r'^(?P<slug>[-\w]+)/$',
        view=place_views.place_detail,
        name='place_detail'),

    url(r'^$',
        view=place_views.place_list,
        name='place_list'),
)

basic/places/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models import permalink
from django.contrib.localflavor.us.models import PhoneNumberField
from tagging.fields import TagField

import tagging


class PlaceType(models.Model):
    """Place types model."""
    title         = models.CharField(_('title'), max_length=100, unique=True)
    slug          = models.SlugField(_('slug'), unique=True)

    class Meta:
        verbose_name = _('place type')
        verbose_name_plural = _('place types')
        db_table = 'place_types'

    class Admin:
        pass

    def __unicode__(self):
        return u'%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('place_type_detail', None, {'slug': self.slug})


class City(models.Model):
    """City model."""
    city          = models.CharField(_('city'), max_length=100)
    state         = models.CharField(_('state'), max_length=100)
    slug          = models.SlugField(_('slug'), unique=True)

    class Meta:
        verbose_name = _('city')
        verbose_name_plural = _('cities')
        db_table = 'place_cities'
        unique_together = (('city', 'state',),)
        ordering = ('state', 'city',)

    class Admin:
       pass

    def __unicode__(self):
        return u'%s, %s' % (self.city, self.state)

    @permalink
    def get_absolute_url(self):
        return ('place_city_detail', None, {'slug': self.slug})


class Point(models.Model):
    """Point model."""
    latitude      = models.FloatField(_('latitude'), blank=True, null=True)
    longitude     = models.FloatField(_('longitude'), blank=True, null=True)
    address       = models.CharField(_('address'), max_length=200, blank=True)
    city          = models.ForeignKey(City)
    zip           = models.CharField(_('zip'), max_length=10, blank=True)
    country       = models.CharField(_('country'), blank=True, max_length=100)

    class Meta:
        verbose_name = _('point')
        verbose_name_plural = _('points')
        db_table = 'place_points'
        ordering = ('address',)

    class Admin:
        list_display  = ('address', 'city', 'zip', 'latitude', 'longitude')
        list_filter   = ('city',)
        search_fields = ('address',)

    def __unicode__(self):
        return u'%s' % self.address


class Place(models.Model):
    """Place model."""
    STATUS_CHOICES = (
        (0, 'Inactive'),
        (1, 'Active'),
    )
    point         = models.ForeignKey(Point)
    prefix        = models.CharField(_('Pre-name'), blank=True, max_length=20)
    title         = models.CharField(_('title'), max_length=255)
    slug          = models.SlugField(_('slug'))
    nickname      = models.CharField(_('nickname'), blank=True, max_length=100)
    unit          = models.CharField(_('unit'), blank=True, max_length=100, help_text='Suite or Apartment #')
    phone         = PhoneNumberField(_('phone'), blank=True)
    url           = models.URLField(_('url'), blank=True, verify_exists=False)
    email         = models.EmailField(_('email'), blank=True)
    description   = models.TextField(_('description'), blank=True)
    status        = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=1)
    created       = models.DateTimeField(auto_now_add=True)
    modified      = models.DateTimeField(auto_now=True)
    place_types   = models.ManyToManyField(PlaceType, blank=True)
    tags          = TagField()

    class Meta:
        verbose_name = _('place')
        verbose_name_plural = _('places')
        db_table = 'places'
        ordering = ('title',)

    class Admin:
        list_display = ('title', 'point', 'city', 'status')
        list_filter = ('status', 'place_types')
        search_fields = ('title',)

    def __unicode__(self):
        return u'%s' % self.full_title

    @property
    def city(self):
        return u'%s' % self.point.city

    @property
    def full_title(self):
        return u'%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('place_detail', None, { 'slug': self.slug } )

    @property
    def longitude(self):
        return self.point.longitude

    @property
    def latitude(self):
        return self.point.latitude

    @property
    def address(self):
        return u'%s, %s %s' % (self.point.address, self.point.city, self.point.zip)

basic/places/views.py
from django.views.generic import list_detail
from basic.places.models import *


def city_detail(request, slug, **kwargs):
    return list_detail.object_detail(
        request,
        queryset = City.objects.all(),
        slug = slug,
        **kwargs
    )
city_detail.__doc__ = list_detail.object_detail.__doc__


def city_list(request, **kwargs):
    return list_detail.object_list(
        request,
        queryset = City.objects.all(),
        paginate_by = 20,
        **kwargs
    )
city_list.__doc__ = list_detail.object_list.__doc__


def place_type_detail(request, slug, **kwargs):
    return list_detail.object_detail(
        request,
        queryset = PlaceType.objects.all(),
        slug = slug,
        **kwargs
    )
place_type_detail.__doc__ = list_detail.object_detail.__doc__


def place_type_list(request, **kwargs):
    return list_detail.object_list(
        request,
        queryset = PlaceType.objects.all(),
        paginate_by = 20,
        **kwargs
    )
place_type_list.__doc__ = list_detail.object_list.__doc__


def place_detail(request, slug, **kwargs):
    return list_detail.object_detail(
        request,
        queryset = Place.objects.all(),
        slug = slug,
        **kwargs
    )
place_detail.__doc__ = list_detail.object_detail.__doc__


def place_list(request, **kwargs):
    return list_detail.object_list(
        request,
        queryset = Place.objects.all(),
        paginate_by = 20,
        **kwargs
    )
place_list.__doc__ = list_detail.object_list.__doc__

basic/places/templates/places/base_places.html
{% extends "base.html" %}


{% block body_class %}places{% endblock %}


{% block body %}
  <div>
    {% block content_title %}{% endblock %}
  </div>
  <div class="content_map">
    {% block content_map %}{% endblock %}
  </div>
  <div class="content">
    {% block content %}{% endblock %}
  </div>
{% endblock %}

basic/places/templates/places/city_detail.html
{% extends "places/base_places.html" %}


{% block title %}Places for {{ object }}{% endblock %}


{% block content_title %}
  <h2>Places for {{ object }}</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    {% for point in object.point_set.all %}
    <li>{% for place in point.place_set.all %}<a href="{{ place.get_absolute_url }}">{{ place.full_title }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    {% endfor %}
  </ul>
{% endblock %}

basic/places/templates/places/city_list.html
{% extends "places/base_places.html" %}


{% block title %}Cities{% endblock %}


{% block content_title %}
  <h2>Cities</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    {% for city in object_list %}
    <li><a href="{{ city.get_absolute_url }}">{{ city }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

basic/places/templates/places/place_detail.html
{% extends "places/base_places.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_id %}place_detail_page{% endblock %}


{% block content_title %}
  <h2>{{ object.full_title }} <em class="phone">{{ object.phone }}</em></h2>
  <h3 class="address">{{ object.point.address }}, <a href="{{ object.point.city.get_absolute_url }}">{{ object.point.city }}</a> {{ object.point.zip }}</h3>
{% endblock %}


{% block content_map %}
  <div id="place_map"></div>
  <script src="http://maps.google.com/maps?file=api&amp;v=2.s&amp;key=ABQIAAAAfeJyb2UVee9F890m28IJbxQCULP4XOMyhPd8d_NrQQEO8sT8XBS4-6jBOOUOr3uKUrxuIjBaT1VikQ" type="text/javascript"></script>
  <script type="text/javascript">
    if (GBrowserIsCompatible()) {
      var latlong = new GLatLng({{ object.latitude }}, {{ object.longitude }});
      var map = new GMap2(document.getElementById("place_map"));
      map.addControl(new GSmallMapControl());
      map.setCenter(latlong, 15);
      map.addOverlay(new GMarker(latlong));
    }
  </script>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    <li><a href="{{ object.url }}">Website</a></li>
    <li><a href="mailto:{{ object.email }}">Email</a></li>
    <li>Type: {% for type in object.place_types.all %}<a href="{{ type.get_absolute_url }}">{{ type }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</li>
  </ul>
  
  {% if object.description %}
  <div class="description">
    <h3>Description</h3>
    {{ object.description|markdown:"safe" }}
  </div>
  {% endif %}
{% endblock %}

basic/places/templates/places/place_list.html
{% extends "places/base_places.html" %}


{% block title %}Places{% endblock %}


{% block content_title %}
  <h2>Places</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    {% for place in object_list %}
    <li><a href="{{ place.get_absolute_url }}">{{ place.title }}</a></li>
    {% endfor %}
  </ul>
  
  {% if is_paginated %}
  <p class="pagination">
    {% if has_next %}
    <a href="?page={{ next }}">Previous</a>
    {% endif %}
    {% if has_next and has_previous %} | {% endif %}
    {% if has_previous %}
    <a href="?page={{ previous }}">Next</a>
    {% endif %}
  </p>
  {% endif %}
{% endblock %}

basic/places/templates/places/placetype_detail.html
{% extends "places/base_places.html" %}


{% block title %}Places for {{ object }}{% endblock %}


{% block content_title %}
  <h2>Places for {{ object }}</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    {% for place in object.place_set.all %}
    <li><a href="{{ place.get_absolute_url }}">{{ place.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

basic/places/templates/places/placetype_list.html
{% extends "places/base_places.html" %}


{% block title %}Place types{% endblock %}


{% block content_title %}
  <h2>Place types</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <ul class="link_list">
    {% for type in object_list %}
    <li><a href="{{ type.get_absolute_url }}">{{ type }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}